# Generated by Django 3.2.4 on 2021-08-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_contactus_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='addStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('umail', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
            ],
        ),
    ]
