# Generated by Django 3.2.4 on 2021-08-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_addstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='id',
        ),
        migrations.AddField(
            model_name='addstudent',
            name='uid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
