# Generated by Django 3.2.4 on 2021-08-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210803_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='uid',
        ),
        migrations.AddField(
            model_name='addstudent',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
